name: openwrt-devmode
version: 1
summary: PoC demo of a OpenWRT snappy solution
description: OpenWRT as a snap for ubuntu core (devinspireexample); use snap install --devmode ...

apps:
 init:
   command: openwrt-init
   plugs: [fullpower]
   daemon: simple
 debug-run:
   command: openwrt-init
   plugs: [fullpower]
 sh:
   command: openwrt-sh
   plugs: [fullpower]

plugs:
  fullpower:
    interface: old-security
    security-template: unconfined

parts:
  openwrt-root:
    plugin: copy
    source: https://people.canonical.com/~asac/ubuntu-core/openwrt-rootfs/latest.tar.gz
    files:
      '*': '.'
  wrapper:
    plugin: copy
    files:
      openwrt-init: openwrt-init
      openwrt-sh: openwrt-sh

